/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
const { error } = require('console');
const fs = require("fs")


const app = express();

app.use(bodyParser.json());

async function findIndex(id){
  try {
    const db = await readDataFromDB()
    for(let i = 0; i < db.length; i++){
      if(parseInt(id)===db[i].id){
        return i
      }
    }
    return -1  
  } catch (error) {
    console.log(error)
  }
  
}

function readDataFromDB(){
  return new Promise((resolve,reject)=>{
    fs.readFile("todos.json","utf-8",(err,data)=>{
      if(err){
        reject(err)
      }else{
        resolve(JSON.parse(data))
      }
    })
  })
}

function writeDataIntoDB(db){
  fs.writeFile("todos.json",JSON.stringify(db),"utf-8",(err)=>{
    if(err){
      console.log(err.message)
    }
  })
}

app.get("/todos",async(req,res)=>{
  try{
    const db = await readDataFromDB()
    res.status(200).json(db)
  }catch{
    console.log(error)
  }
  
})

app.get("/todos/:id",async(req,res)=>{
  let id = req.params.id
  const db = await readDataFromDB()
  let todoItem =  db[await findIndex(id)]
  
  if(todoItem){
    res.status(200).json(todoItem)
  }else{
    res.status(404).send("404 Not Found")
  }
})

app.post("/todos",async(req,res)=>{
  const newTodo = {
    id : Math.floor(Math.random() * 1000),
    title : req.body.title,
    completed : req.body.completed,
    description : req.body.description
  }
  
  const db = await readDataFromDB()

  db.push(newTodo)

  writeDataIntoDB(db)

  res.status(201).json(newTodo)
})

app.put("/todos/:id",async(req,res)=>{
  let id = req.params.id
  let index = await findIndex(id)
  const db = await readDataFromDB()
  if(db[index]){
    
    db[index].title = req.body.title
    db[index].completed = req.body.completed
    db[index].description = req.body.description

    writeDataIntoDB(db)

    res.status(200).send("Updated todo")
  }else{
    res.status(404).send("404 Not Found")
  }
})

app.delete("/todos/:id",async(req,res)=>{
  let id = req.params.id
  let index = await findIndex(id)
  const db = await readDataFromDB()
  
  if(db[index]){
    db.splice(index,1)
    
    writeDataIntoDB(db)
    
    res.status(200).send("Deleted Todo")
  }else{
    res.status(404).send("404 Not Found")
  }
})

app.use((req,res)=>{
  res.status(401).send("Invalid routes")
})


// app.listen(3000)
module.exports = app;